version: "3.8"
services:
  weapi:
    build: .
    container_name: weapi
    ports:
      - "8081:3000"   # host:container, usa 8081 porque 3000 ya est√° ocupado
    restart: always
    volumes:
      - ./session:/usr/src/app/session

